Prova-Luiz Eduardo
univas/2016-si6-secondcall-exam pull request #1
Opened 2016-12-08 23:50 UTC by oluizeduardo

2016-12-13 05:12 UTC, edysegura requested changes
Olá @oluizeduardo !

Seguem os meus comentários sobre a sua avaliação! Me retorne assim que possível.

Abraços,

2016-12-13 05:12 UTC, edysegura commented on app/employee.js
> +            res.json({error: 'Não encontrado!!'})
Você se inspirou na [avaliação](https://github.com/armgalison/2016-si6-secondexam/blob/72b38d1bf14c587e3ac0e3bc13cdc16316c7a2a6/app/students.js#L36) do @armgalison para fazer a sua avaliação? A estrutura está muito similar e eu não tinha ensinado essa abordagem em aula.

A sua nota está bloqueada até que você justifique como você chegou nessa estrutura.

2016-12-13 05:12 UTC, edysegura commented on app/employee.js
> +            res.json({error: 'Não encontrado!!'})
A consulta à internet é liberada mas não ao material do colega de sala! Eu deixo isso bem claro em todas as avaliações.

2016-12-13 05:12 UTC, edysegura commented on server.js
> +
Falta incluir e fazer o uso da rota que foi implementada em employee.js

2016-12-13 05:12 UTC, edysegura commented on server.js
> +const port = 8080
Qual a motivação do uso da porta 8080?

2016-12-13 05:12 UTC, edysegura commented on public/js/employeeController.js
> +            url: "/api/employee/" + id
A mesma [recomendação](https://github.com/univas/2016-si6-secondexam/pull/4#discussion-diff-92095536R7) que fiz para o @WellingtonBraga se aplica aqui.

Qual foi a sua motivação de mudar essa request que atendia as boas práticas de implementação REST?

2016-12-13 05:12 UTC, edysegura commented on server.js
> +const bodyParser = require("body-parser")
Como você não incluiu as dependências acima ao _package.json_ não foi possível executar a sua avaliação.

![image](https://cloud.githubusercontent.com/assets/5324414/21128377/b1d7cd0a-c0e1-11e6-9400-4e414b76fccf.png)

2016-12-13 05:17 UTC, closed without merging

2016-12-13 12:56 UTC, oluizeduardo commented on app/employee.js
> +            res.json({error: 'Não encontrado!!'})
Oi Edy. Eu vi a avaliação anterior e tentei refazer. Eu usei o repositório da prova, o site do Express, o site NodeBR, o nosso repositório do Pokemon e anotações de aula. Quanto a essas linhas, foi algo que eu anotei pois achei interessante fazer essa validação no servidor. Também vi algo assim no site do Express.

2016-12-13 12:58 UTC, oluizeduardo commented on server.js
> +const bodyParser = require("body-parser")
O quanto isso me prejudica?

2016-12-13 13:04 UTC, oluizeduardo commented on server.js
> +const port = 8080
Mistura de aleatório com aula. Acho que nas aulas nós usamos a 8000 não é?
8080 é porta de HTTP, correto? Gera algum problema na aplicação se eu usar uma porta que já é usada por outra aplicação/serviço?

2016-12-13 13:06 UTC, oluizeduardo commented on public/js/employeeController.js
> +            url: "/api/employee/" + id
Se eu não me engano, eu mudei a letra por causa do nome do arquivo, em vez de employees era employee.

2016-12-13 13:10 UTC, oluizeduardo commented on public/js/employeeController.js
> +            url: "/api/employee/" + id
Olhei aqui, acho que eu devo ter confundido app com api, porque dentro de app tem o arquivo employee.js. Troquei a letra achando que estava escrito errado.

2016-12-13 20:36 UTC, edysegura commented on server.js
> +const port = 8080
A porta que utilizamos em aula ou era [3000](https://github.com/univas/2016-pokedex/blob/master/server.js#L22) ou [9000](https://github.com/univas/http-server/blob/master/server.js#L6). A porta 8080 é reservada para alguns tipos de web services e para hosting pessoal, o único problema é um possível conflito ao implantar a aplicação em algum servidor.

2016-12-13 21:11 UTC, edysegura commented on app/employee.js
> +            res.json({error: 'Não encontrado!!'})
Foi [nessa página](http://expressjs.com/en/guide/error-handling.html) que você viu?

2016-12-13 21:15 UTC, edysegura commented on app/employee.js
> +        let findedEmployee = findEmployee(requestId)
E como você me explica a mesma nomenclatura de variáveis??

![image](https://cloud.githubusercontent.com/assets/5324414/21159465/75dec83a-c168-11e6-8ff6-d0af1ce62168.png)

2016-12-13 21:20 UTC, edysegura commented on server.js
> +const bodyParser = require("body-parser")
Sua avaliação simplesmente não executou.

2016-12-13 23:17 UTC, oluizeduardo commented on app/employee.js
> +            res.json({error: 'Não encontrado!!'})
Foi aí sim! Comecei a ver o Express por aí depois da primeira prova. Para refazer a segunda prova eu  também usei a parte que ensina rotas. Também usei o site do GUJ como referência.

2016-12-13 23:29 UTC, oluizeduardo commented on server.js
> +const bodyParser = require("body-parser")
Aí foi falta de atenção minha... Sei que é fácil de resolver. Adiciona a versão correta do Express no package.json; somente uma linha. Nem era difícil isso, eu que nem lembrei mesmo. 

Quando eu dou `npm install Express` ele apenas baixa os pacotes e adiciona temporariamente no meu projeto, mas não faz nada na lista de dependências no package.json, correto? Porque só com o npm funcionou comigo. 
A intenção na correção da prova é que você não dê o npm install em nada e ele baixe tudo descrito na lista de dependências??

2016-12-13 23:40 UTC, oluizeduardo commented on app/employee.js
> +        let findedEmployee = findEmployee(requestId)
Ambas as provas têm o mesmo objetivo: encontrar alguém. A referência que eu tinha para fazer a prova 2.2 era o Pokemon e as resoluções da prova 2.1.

2016-12-14 15:09 UTC, edysegura commented on app/employee.js
> +        let findedEmployee = findEmployee(requestId)
No [exemplo do pokemon](https://github.com/univas/2016-pokedex/blob/master/app/pokeApi.js) que desenvolvemos em laboratório tem uma estrutura diferente do apresentado em sua avaliação. 

Colocando o código lado a lado é possível constatar que você copiou a estrutura do @armgalison. Veja a imagem abaixo:

![image](https://cloud.githubusercontent.com/assets/5324414/21187058/c3e68c94-c1fd-11e6-9f7e-671a32852c77.png)